Delete MyApplication and add new project App by maven generate
PlatonAnn/qa-automation-java pull request #3
Opened 2021-08-11 14:57 UTC by PlatonAnn

Delete MyApplication and add new project App by maven generate

2021-08-12 09:38 UTC, Campi001 commented on src/test/java/com/tinkoff/edu/AppTest.java
> +{
По общепринятому код-стайлу открывающая "{" должна находиться на той же строке, что объявление класса/метода ([Java Code Conventions](https://www.oracle.com/technetwork/java/codeconventions-150003.pdf) обрати внимание на п. 6.4). К сожалению, при генерации проекта через `mvn archetype:generate` эти правила не учитываются.
Быстро поправить формат в соответствии с правилами ты можешь в идее с помощью хоткея **ctrl+alt+L** (на винде)

2021-08-12 09:41 UTC, Campi001 commented on src/main/java/com/tinkoff/edu/App.java
> +{
Те же замечания по код-стайлу, что в AppTest.java) тоже нужно воспользоваться автоформатированием

2021-08-12 10:05 UTC, Campi001 commented on app.iml
> +<?xml version="1.0" encoding="UTF-8"?>
*.iml файлы являются служебными файлами идеи, и считается хорошим тоном добавлять их в .gitignore (подобно .idea). Попробуй сделать следующее:
1. добавь в .gitignore новую строку *.iml (для игнора всех файлов с таким расширением)
2. в терминале выполни `git rm --cached app.iml` - эта команда удалит .iml файл из отслеживаемых, но оставит его у тебя локально
3. запуш изменения

В репо должен появиться обновленный .gitignore, .iml файл должен пропасть

2021-08-12 10:18 UTC, Campi001 commented
Также убедись, что идея распознает твою структуру проекта правильно (могут быть некоторые проблемы при генерации через mvn archetype:generate, особенно на уже существующем проекте). Структура должна выглядеть так:
![image](https://user-images.githubusercontent.com/42438795/129180153-e6fde438-c672-4051-984d-aa6b16357749.png)
Папка main/java - src root, папка test/java - test src root. Пометить нужные папки как _src/test src root_ ты можешь, нажав правую кнопку мыши на папке, далее Mark Directory as - нужный тип

2021-08-12 10:29 UTC, Campi001 requested changes
Структура проекта создана верно, с pom.xml все хорошо) Есть пара замечаний касательно код-стайла (не твоя вина, но нужно поправить), а также обрати внимание на замечание по app.iml

2021-08-13 12:07 UTC, PlatonAnn commented on src/test/java/com/tinkoff/edu/AppTest.java
> +{
спасибо за ссылку, учту!

2021-08-13 12:10 UTC, PlatonAnn commented on app.iml
> +<?xml version="1.0" encoding="UTF-8"?>
вот это крутое замечание, спасибо, исправлю)

2021-08-13 12:35 UTC, merged