Add business rules and tests for controller (HomeWork№8)
PlatonAnn/qa-automation-java pull request #7
Opened 2021-09-05 13:33 UTC by PlatonAnn

HomeWork№8

2021-09-06 17:29 UTC, Campi001 commented on src/main/java/com/tinkoff/edu/app/LoanCalcController.java
> +        LoanResponse loanResponse = new LoanResponse(LoanResponseType.ERROR, -1);
тут 2 момента:
1. лучше отделять блоки с объявлением переменных и условными конструкциями/циклами/остальной логикой, т.к. визуально все смешивается и получается "каша", в которой сложно сходу разобраться стороннему человеку
2. необходим ли здесь loanResponse как отдельная переменная вне условий? Выглядит так, что можно обойтись без нее, просто возвращая результат createRequest

2021-09-06 17:31 UTC, Campi001 commented on src/main/java/com/tinkoff/edu/app/LoanCalcController.java
> +        } else if (((request.getType() == PersonEmploymentType.PERSON)
Когда получаются такие длинные условия, считается хорошей практикой выносить их в отдельные константы. Попробуй вынести

2021-09-06 17:39 UTC, Campi001 commented on src/main/java/com/tinkoff/edu/app/LoanCalcController.java
> +        } else if (((request.getType() == PersonEmploymentType.PERSON)
Здесь в каждом else if ты возвращаешь результат - это ок, ошибки в этом нет, просто отмечу, что в таких кейсах можно каждый условный блок заключать в обычный if - во многих случаях это улучшает читаемость.
Это можно не править, просто fyi)

if-return statement выглядит так:
if (x) {
    return a;
}
if (y) {
    return b;
}
return c;

2021-09-06 17:41 UTC, Campi001 commented on src/main/java/com/tinkoff/edu/app/LoanCalcController.java
> +            loanResponse = loanCalcService.createRequest(request, LoanResponseType.APPROVED);
как раз то, про что я говорила в первом комменте - можно обойтись без присвоения в loanResponse

2021-09-06 17:42 UTC, Campi001 commented on src/main/java/com/tinkoff/edu/app/LoanCalcController.java
> +        if (request.getMonths() <= 0 || request.getAmount() <= 0) {
Очень хорошо, что сразу предусмотрела эти кейсы, молодец!)

2021-09-06 18:04 UTC, Campi001 commented on src/main/java/com/tinkoff/edu/app/LoanCalcService.java
> +    public LoanResponse createRequest(LoanRequest request, LoanResponseType responseType) {
тут, кажется, проблема с неймингом: метод называется createRequest, но на вход уже подается готовый request

2021-09-06 18:09 UTC, Campi001 commented on src/main/java/com/tinkoff/edu/app/LoanCalcService.java
> +        LoanResponse loanResponse = new LoanResponse(responseType, requestId);
можно сразу вернуть new LoanResponse, без присваивания (IDE кстати должна подсвечивать подобные места в коде)

2021-09-06 18:21 UTC, Campi001 commented on src/test/java/com/tinkoff/edu/LoanCalcTest.java
> +        request = new LoanRequest(PersonEmploymentType.OOO, 10, 1000);
а зачем ты в beforeEach хуке сетаешь реквест, если далее в каждом тесте ты его снова переопределяешь?) Кажется, есть смысл сделать request локальной переменной для каждого теста, т.к. везде разные входные параметры

2021-09-06 18:25 UTC, Campi001 requested changes
Круто сдизайнила тесты, мое почтение) Но можно кое-что улучшить:
Во-первых, обрати внимание на комменты)
во-вторых, у нас в пакете app стало очень много классов, кажется, настала пора разделить их по пакетам. По крайней мере точно можно выделить пакет controllers (и по аналогии)

2021-09-09 13:31 UTC, PlatonAnn commented on src/main/java/com/tinkoff/edu/app/LoanCalcController.java
> +        } else if (((request.getType() == PersonEmploymentType.PERSON)
спасибо, учту

2021-09-10 07:47 UTC, PlatonAnn commented on src/main/java/com/tinkoff/edu/app/LoanCalcController.java
> +        LoanResponse loanResponse = new LoanResponse(LoanResponseType.ERROR, -1);
обсудили

2021-09-24 13:12 UTC, Campi001 approved these changes

2021-09-24 13:12 UTC, merged